### PR TITLE
[GH-735] Adjusted commitment hash function

### LINKED ISSUE #735: Adjust commitment hash calculations in naming system
To be Hash(NameHash(name) + name_salt) instead of Hash(Hash(name + name_salt))

### PR DESCRIPTION
**Pull request by Artur64**
Resolves #735 . Should be tested and merged after #782 is merged.

### CODE REVIEW

**Review by thepiwo — COMMENTED** [review]
Did you check if the commitment hash is the same as in epoch? For the old version it was the same as in epoch 0.16. but now the logic for hash creation is changed. Is this as intended?

**Comment by Artur64** [comment]
@thepiwo  I'm going to test hashes after all blockers are merged in master, as i mentioned before in the description of this PR.

**Comment by cytadela8** [comment]
I think it would be nice if you add a simple test that creates a hash using our code of (for example) "exampledomain.test" and compares it against a hash you obtained manually in epoch. This way we make sure everything will stay working as expected even if we make some changes to Naming. 

This is of course to be done after the issue is unblocked.

**Comment by Artur64** [comment]
@thepiwo Commitment hashes being produced by our and Epoch's node are equal, so i'm ready with this PR.

**Review by DanielaIvanova — APPROVED** [review]

**Review by thepiwo — APPROVED** [review]

**Pull request merged**
