### PR TITLE
[GH-707] Adjust contract_call_tx function

### LINKED ISSUE #707: Adjust contract_call_tx function
Currently, contract call transaction is not being mined by Epoch's node, which means, that there is no compatibility to epoch.

### PR DESCRIPTION
**Pull request by cheezus1**
Call contract tx is now being successfully synced with epoch as well.

Resolves #707

### CODE REVIEW

**Comment by cheezus1** [comment]
Yes, that was the purpose.
What I had missed is that the REVERT opcode wasn't terminating the execution, which caused more gas to be used on our node. There were some values that were not deserialized as well.

**Comment by thepiwo** [comment]
@DanielaIvanova could you provide the commands you test with?

**Comment by thepiwo** [comment]
@cheezus1 Tests are still failing

**Comment by cheezus1** [comment]
We can merge this now. Contract tests will be re-enabled after issue #712

**Comment by thepiwo** [comment]
@cheezus1 please disable the test using the disabled tag, not commenting the file out...

**Pull request merged**
