### PR TITLE
[GH-#357] Adjust Oracles structure to match Erlang implementation

### PR DESCRIPTION
**Pull request by d-velev**

### CODE REVIEW

**Comment by Artur64** [comment]
Why query_format and response_format are still maps? In Epoch specs , both of these fields are binaries, "Utf8 encoded string". I cant encode maps with RLP,  but i can provide a workaround - convert these maps to jsons (Poison library return jsons as a string in Elixir) and encode them with RLP. The downside of this workaround might be in utf8 encoding, as i mentioned before they expect a "Utf8 encoded string", not a structure.

**Comment by d-velev** [comment]
They haven't implemented query/response validation in epoch yet since they are waiting for the contract team to do the necessary preparations there (they are going to use types from the contract language) so there is no way to replicate their query/response handling

**Comment by Artur64** [comment]
Ok, so, @thepiwo whats your opinion?

**Comment by thepiwo** [comment]
If strings are "compatible" for now, lets use them, otherwise merge as is

**Comment by cytadela8** [comment]
@thepiwo I merged, but for some reason I get " Invalid query or response format definition:" in Oracle registration now.

**Comment by cytadela8** [comment]
Note: my transaction refactoring fixed an error that might have caused format to always be considered correct, although that doesn't justify how tests pass on master.

**Comment by thepiwo** [comment]
@d-velev can you look into the issues, @cytadela8 mentioned?

**Comment by thepiwo** [comment]
what is the state of this?

**Pull request merged**
