### PR TITLE
[GH-#341] use patricia merkle tree as accounts_state merkle tree implementation

### LINKED ISSUE #341: use patricia merkle tree as accounts_state merkle tree implementation
depended on #345 and #317 to be merged

### PR DESCRIPTION
**Pull request by DanielaIvanova**
Resolves #341 #365

### CODE REVIEW

**Comment by thepiwo** [comment]
@d-velev will you review?

**Comment by DanielaIvanova** [comment]
@cytadela8 
I have tested the persistence and everything is working properly.

**Comment by cytadela8** [comment]
ok, I will test persistence and respond then.

**Comment by cytadela8** [comment]
I added a small change to chainstate persistence test.

**Pull request merged**
