### PR TITLE
[GH-#264] added elixir formatter config

### LINKED ISSUE #264: Include Elixir 1.6 formatter config

### PR DESCRIPTION
**Pull request by thepiwo**
closes #264

### CODE REVIEW

**Comment by thepiwo** [comment]
merge after #263

**Comment by thepiwo** [comment]
@gspasov @meivantodorov can you review this?
this forces everybody to commit formatted code, but is dependent on the elixir version, for now 1.6.2

**Comment by thepiwo** [comment]
@gspasov @meivantodorov @d-velev would you prefer any changes to `.formatter.exs`

**Comment by gspasov** [comment]
@thepiwo What if the default formatting of the code is not the most suitable one in some cases?

**Comment by thepiwo** [comment]
@gspasov then we can adjust the formatter config to handle it, otherwise stick to it.

**Pull request merged**
