### PR TITLE
[GH-638] Channel compatibility testing docs

### LINKED ISSUE #638: add erlang compatibility documentation for channels

### PR DESCRIPTION
**Pull request by cytadela8**
resolves #638

### CODE REVIEW

**Comment by thepiwo** [comment]
@cytadela8 there is a lot of unneeded `\` in the examples

**Comment by cytadela8** [comment]
I can remove them. I added them, because all the `_` were red in my editor.

**Comment by thepiwo** [comment]
@cytadela8 yes, can you do so

**Comment by thepiwo** [comment]
lets merge at the same time with https://github.com/aeternity/elixir-node/pull/586

**Pull request merged**
