### PR TITLE
[GH-#408] removed halt-exit-status for dialyzer in travis.yml

### LINKED ISSUE #408: Remove --halt-exit-status for dialyzer

### PR DESCRIPTION
**Pull request by 0legIv**
resolves #408

### CODE REVIEW

**Comment by d-velev** [comment]
We don't need the dialyzer.ignore-warnings file now as well right?

**Comment by 0legIv** [comment]
@d-velev I think we need it, because some of the errors are about unknown functions from another modules like this `:0: Unknown function 'Elixir.Aewallet.KeyPair':compress/1`. Dialyzer just can't see them, so they create some mess

**Comment by thepiwo** [comment]
@0legIv we may need some of it, but just things that don't change the line numbers, so please clean or remove completely

**Comment by thepiwo** [comment]
@meivantodorov can you review?

**Pull request merged**
