### PR TITLE
[GH-530] Replaced all t() with their full name in the same module

### LINKED ISSUE #530: adjust to full type specifications instead of only t() in same module

### PR DESCRIPTION
**Pull request by NikolaiDimitrov**
resolve #530

### CODE REVIEW

**Comment by cytadela8** [comment]
Grep returned following instances of `t()`:
```
grep -r "(t()"                                                                                                                                    20  19:26 
aecore/lib/aecore/tx/data_tx.ex:  @spec fee(t()) :: non_neg_integer()
aecore/lib/aecore/tx/data_tx.ex:  @spec senders(t()) :: list(binary())
aecore/lib/aecore/tx/data_tx.ex:  @spec main_sender(t()) :: binary() | nil
aecore/lib/aecore/tx/data_tx.ex:  @spec nonce(t()) :: non_neg_integer()
aecore/lib/aecore/tx/data_tx.ex:  @spec ttl(t()) :: non_neg_integer()
aecore/lib/aecore/tx/data_tx.ex:  @spec payload(t()) :: map()
aecore/lib/aecore/tx/data_tx.ex:  @spec validate(t(), non_neg_integer()) :: :ok | {:error, String.t()}
aecore/lib/aecore/tx/signed_tx.ex:  @spec validate(t()) :: :ok | {:error, String.t()}
aecore/lib/aecore/tx/signed_tx.ex:  @spec validate(t(), non_neg_integer()) :: :ok | {:error, String.t()}
aecore/lib/aecore/oracle/tx/oracle_extend_tx.ex:  @spec validate(t(), DataTx.t()) :: :ok | {:error, String.t()}
aecore/lib/aecore/oracle/tx/oracle_query_tx.ex:  @spec validate(t(), DataTx.t()) :: :ok | {:error, String.t()}
aecore/lib/aecore/oracle/tx/oracle_query_tx.ex:  @spec is_minimum_fee_met?(t(), non_neg_integer(), non_neg_integer() | nil) :: boolean()
aecore/lib/aecore/oracle/tx/oracle_registration_tx.ex:  @spec validate(t(), DataTx.t()) :: :ok | {:error, String.t()}
aecore/lib/aecore/oracle/tx/oracle_registration_tx.ex:  @spec is_minimum_fee_met?(t(), non_neg_integer(), non_neg_integer()) :: boolean()
aecore/lib/aecore/oracle/tx/oracle_response_tx.ex:  @spec validate(t(), DataTx.t()) :: :ok | {:error, String.t()}
aecore/lib/aecore/oracle/tx/oracle_response_tx.ex:  @spec is_minimum_fee_met?(t(), non_neg_integer()) :: boolean()
aecore/lib/aecore/oracle/oracle.ex:  @spec encode_to_list(t()) :: list()
aecore/lib/aecore/account/account.ex:  @spec encode_to_list(t()) :: list() | {:error, String.t()}
aecore/lib/aecore/chain/identifier.ex:  @spec encode_list_to_binary(list(t())) :: list(binary())
aecore/lib/aecore/chain/identifier.ex:  @spec decode_list_from_binary(list(binary())) :: {:ok, list(t())} | {:error, String.t()}
aecore/lib/aecore/naming/tx/name_transfer_tx.ex:  @spec validate(t(), DataTx.t()) :: :ok | {:error, String.t()}
aecore/lib/aecore/naming/tx/name_revoke_tx.ex:  @spec validate(t(), DataTx.t()) :: :ok | {:error, String.t()}
aecore/lib/aecore/naming/tx/name_pre_claim_tx.ex:  @spec validate(t(), DataTx.t()) :: :ok | {:error, String.t()}
aecore/lib/aecore/naming/tx/name_update_tx.ex:  @spec validate(t(), DataTx.t()) :: :ok | {:error, String.t()}
aecore/lib/aecore/naming/tx/name_claim_tx.ex:  @spec validate(t(), DataTx.t()) :: :ok | {:error, String.t()}
```

**Comment by cytadela8** [comment]
There might be more due to the way I was searching.

**Comment by NikolaiDimitrov** [comment]
@cytadela8 Now everything is replaced. All files are double-checked

**Comment by thepiwo** [comment]
whats the status here?

**Comment by NikolaiDimitrov** [comment]
@thepiwo waiting for review

**Pull request merged**
